name = "api-keys"
main = "src/index.ts"
compatibility_date = "2023-12-18"
tsconfig = "tsconfig.wrangler.json"

[vars]
ENVIRONMENT = "development"
# The local machine running wrangler dev.
ALLOWED_ORIGINS = "http://localhost:8787"
# Testing and passthrough keys for automation.
ALLOWED_AUTH_KEYS = "key1,key2,key3"

[[kv_namespaces]]
binding = "API_KEYS"
id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

[env.prod.vars]
ENVIRONMENT = "production"
# In production, temporarily, use this test domain. If folk spam it, we can
# test that functionality too.
ALLOWED_ORIGINS = "https://api-keys-prod.softwarepatterns.workers.dev"
# In production, no test or passthrough keys should be allowed.
ALLOWED_AUTH_KEYS = ""

[[env.prod.kv_namespaces]]
# Safe to commit and expose since outsiders can't use it.
binding = "API_KEYS"
id = "b5a0a513426a4a6db77617804f3dae2e"
