name = "static-sites"
main = "src/index.ts"
compatibility_date = "2023-12-18"
tsconfig = "tsconfig.wrangler.json"

[vars]
PURGE_TOKEN = "abc123"

[[r2_buckets]]
binding = 'StaticSitesR2'
bucket_name = 'static-sites'

[[kv_namespaces]]
binding = "RedirectsKV"
id = "ba4c73bb8c2347a680a0d9094da087c4"
